/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal_prometheus_palenquemolina_jhoelkevin.view;

import com.mycompany.proyectofinal_prometheus_palenquemolina_jhoelkevin.controller.FavoritoController;
import com.mycompany.proyectofinal_prometheus_palenquemolina_jhoelkevin.controller.LibroController;
import com.mycompany.proyectofinal_prometheus_palenquemolina_jhoelkevin.model.Libro;
import com.mycompany.proyectofinal_prometheus_palenquemolina_jhoelkevin.model.Usuario;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicPanelUI;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isard
 */
public class VentanaFavoritos extends javax.swing.JFrame {

    private Usuario usuarioActivo;
    private FavoritoController favoritoController;
    private LibroController libroController;
    private DefaultTableModel tablaModel;

    public VentanaFavoritos(Usuario usuario) {
        initComponents();  // Inicializa los componentes autogenerados
        setLocationRelativeTo(null);

        // Carga la imagen de fondo desde resources
        Image bg = null;
        try {
            URL url = getClass().getResource("/pochita.png");
            bg = ImageIO.read(url);
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Le inyectamos a jPanel3 un UI que la dibuje como fondo
        final Image background = bg;
        jPanel3.setUI(new BasicPanelUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                // Primero dibuja la imagen a escala completa
                if (background != null) {
                    g.drawImage(
                      background,
                      0, 0,
                      c.getWidth(), c.getHeight(),
                      c
                    );
                }
                // Luego deja que el panel dibuje el resto de componentes
                super.paint(g, c);
            }
        });
        
        
        
        // Crear y asignar modelo de tabla con 3 columnas
        tablaModel = new DefaultTableModel(
            new Object[][] {},
            new String[] { "Portada", "Título", "Autor" }
        ) {
            Class<?>[] types = new Class<?>[]{ ImageIcon.class, String.class, String.class };
            @Override public Class<?> getColumnClass(int columnIndex) { return types[columnIndex]; }
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        tblFavoritos.setModel(tablaModel);

        // Ajustar altura de fila para portadas
        tblFavoritos.setRowHeight(120);

        // Centrar texto en columnas Título (1) y Autor (2)
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        tblFavoritos.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblFavoritos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);

        // Inicializar controladores y usuario
        this.usuarioActivo     = usuario;
        favoritoController      = new FavoritoController();
        libroController         = new LibroController();

        // Cargar tabla con portadas
        cargarTablaFavoritos();
        
        //Desactivar edición de la tabla
        tblFavoritos.setDefaultEditor(Object.class, null);
        tblFavoritos.setRowHeight(120);
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);
        tblFavoritos.getColumnModel().getColumn(1).setCellRenderer(center);
        tblFavoritos.getColumnModel().getColumn(2).setCellRenderer(center);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void cargarTablaFavoritos() {
        tablaModel.setRowCount(0);
        List<Libro> lista = favoritoController.obtenerFavoritos(usuarioActivo.getId());
        for (Libro l : lista) {
            ImageIcon icono = crearIconoPortada(l.getPortadaURL());
            tablaModel.addRow(new Object[]{ icono, l.getTitulo(), l.getAutor() });
        }
    }
    
    
    /**
     * Dado el string ruta , devuelve un ImageIcon escalado.
     */
    private ImageIcon crearIconoPortada(String ruta) {
        try {
            URL url;
            if (ruta.startsWith("http://") || ruta.startsWith("https://") || ruta.startsWith("file:")) {
                url = new URL(ruta);
            } else {
                // Intentamos cargar como recurso en classpath /images/
                URL r = getClass().getResource("/images/" + ruta);
                if (r != null) {
                    url = r;
                } else {
                    // Finalmente lo tratamos como fichero local
                    url = new File(ruta).toURI().toURL();
                }
            }
            Image img = ImageIO.read(url).getScaledInstance(80, 120, Image.SCALE_SMOOTH);
            return new ImageIcon(img);
        } catch (IOException e) {
            // Fallback: icono por defecto si existe
            URL def = getClass().getResource("/images/defaultCover.png");
            if (def != null) {
                try {
                    Image img = ImageIO.read(def).getScaledInstance(80, 120, Image.SCALE_SMOOTH);
                    return new ImageIcon(img);
                } catch (IOException ex) { }
            }
            return null;
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerDetalles = new javax.swing.JButton();
        btnVolverBiblioteca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFavoritos = new javax.swing.JTable();
        btnQuitarFavorito = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnVerDetalles.setBackground(new java.awt.Color(102, 255, 255));
        btnVerDetalles.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerDetalles.setText("Ver detalles");
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });

        btnVolverBiblioteca.setBackground(new java.awt.Color(255, 255, 0));
        btnVolverBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolverBiblioteca.setText("Volver a Biblioteca");
        btnVolverBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverBibliotecaActionPerformed(evt);
            }
        });

        tblFavoritos.setBackground(new java.awt.Color(51, 51, 51));
        tblFavoritos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 3, true));
        tblFavoritos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblFavoritos.setForeground(new java.awt.Color(255, 255, 0));
        tblFavoritos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblFavoritos);

        btnQuitarFavorito.setBackground(new java.awt.Color(204, 0, 0));
        btnQuitarFavorito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuitarFavorito.setForeground(new java.awt.Color(255, 255, 255));
        btnQuitarFavorito.setText("Quitar de Favoritos");
        btnQuitarFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarFavoritoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 4, true));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Tus Favoritos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnQuitarFavorito)
                                    .addComponent(btnVolverBiblioteca)
                                    .addComponent(btnVerDetalles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnVerDetalles)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarFavorito)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolverBiblioteca)
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        int fila = tblFavoritos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un libro favorito", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String titulo = (String) tablaModel.getValueAt(fila, 1);
        int idLibro = libroController.obtenerIdPorTitulo(titulo);
        if (idLibro != -1) {
            Libro libro = libroController.obtenerPorId(idLibro);
            VentanaLibroDetalles detallesWin = new VentanaLibroDetalles(libro, usuarioActivo);
            detallesWin.setVisible(true);
        }
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnQuitarFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarFavoritoActionPerformed
        int fila = tblFavoritos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un libro favorito para quitar", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String titulo = (String) tablaModel.getValueAt(fila, 1);
        int idLibro = libroController.obtenerIdPorTitulo(titulo);
        if (idLibro != -1) {
            boolean ok = favoritoController.eliminarFavorito(usuarioActivo.getId(), idLibro);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Libro quitado de favoritos");
                cargarTablaFavoritos();
            }
        }
    }//GEN-LAST:event_btnQuitarFavoritoActionPerformed

    private void btnVolverBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverBibliotecaActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVolverBibliotecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitarFavorito;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JButton btnVolverBiblioteca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFavoritos;
    // End of variables declaration//GEN-END:variables
}
